name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main, develop]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      has-vercel-secrets: ${{ steps.check.outputs.has-secrets }}
    steps:
      - name: Check if Vercel secrets are configured
        id: check
        run: |
          if [[ "${{ secrets.VERCEL_TOKEN }}" != "" && "${{ secrets.VERCEL_ORG_ID }}" != "" && "${{ secrets.VERCEL_PROJECT_ID }}" != "" ]]; then
            echo "has-secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has-secrets=false" >> $GITHUB_OUTPUT
          fi

  deploy-staging:
    needs: [check-secrets]
    if: ${{ needs.check-secrets.outputs.has-vercel-secrets == 'true' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Deploy to Vercel (Staging)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        scope: ${{ secrets.VERCEL_ORG_ID }}
        alias-domains: staging.myapp.com

  deploy-production:
    needs: [check-secrets]
    if: ${{ needs.check-secrets.outputs.has-vercel-secrets == 'true' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Deploy to Vercel (Production)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        scope: ${{ secrets.VERCEL_ORG_ID }}
        alias-domains: myapp.com
    
    - name: Notify deployment success
      if: ${{ success() }}
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        message: 'Production deployment successful! 🚀'

  skip-deploy:
    needs: [check-secrets]
    if: ${{ needs.check-secrets.outputs.has-vercel-secrets == 'false' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Skip deployment
        run: |
          echo "Skipping deployment - Vercel secrets not configured"
          echo "To enable automatic deployment, configure VERCEL_TOKEN, VERCEL_ORG_ID, and VERCEL_PROJECT_ID secrets" 